let Userdatas = [
  {
    username: "علی",
    id: 1,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "124.32$",
    email: "ali@gmail.com",
    pass: "1234",
  },
  {
    username: "عرشیا",
    id: 2,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "944.51$",
    email: "arshia@gmail.com",
    pass: "1235",
  },
  {
    username: "سوگند",
    id: 3,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "255.11$",
    email: "sogand@gmail.com",
    pass: "1236",
  },
  {
    username: "ماهان",
    id: 4,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "22.65$",
    email: "mahan@gmail.com",
    pass: "1237",
  },
  {
    username: "رضا",
    id: 5,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "522.00$",
    email: "reza@gmail.com",
    pass: "1238",
  },
  {
    username: "محمدرضا",
    id: 6,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "52.65$",
    email: "mohamadreza@gmail.com",
    pass: "1238",
  },
  {
    username: "محمد",
    id: 7,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "99.5$",
    email: "mohamad@gmail.com",
    pass: "1234",
  },
  {
    username: "سامان",
    id: 8,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "33.2$",
    email: "saman@gmail.com",
    pass: "1234",
  },
  {
    username: "سام",
    id: 9,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "3.66$",
    email: "sam@gmail.com",
    pass: "1234",
  },
  {
    username: "مریم",
    id: 10,
    img: "./App/Pics/profilepic.jpg",
    status: "غیرفعال",
    transaction: "883.66$",
    email: "maryam@gmail.com",
    pass: "1234",
  },
];

export { Userdatas };
